default: &default
  adapter: mysql2
  encoding: <%= ENV["DB_ENCODING"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_SERVER_IP"] %>
  port: <%= ENV["DB_SERVER_PORT"] %>

development:
  <<: *default
  database: <%= ENV["DB_DEV_NAME"] %>

test:
  <<: *default
  database: <%= ENV["DB_TEST_NAME"] %>

production:
  <<: *default
  database: <%= ENV["DB_PROD_NAME"] %>
